services:
  test-app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - REDIS_OM_URL=redis://redis:6379
    ports:
      - "80:80"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    